name: reel_ro
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  aws_s3_upload: ^1.4.0
  better_player: ^0.0.83
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_messaging: ^12.0.2
  flutter:
    sdk: flutter
  flutter_emoji: ^2.4.0
  flutter_keyboard_visibility: ^5.3.0
  font_awesome_flutter: ^10.1.0
  get: 4.6.5
  get_storage: ^2.0.3
  google_sign_in: ^5.3.1
  http: ^0.13.4
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+6
  intl: null
  package_info_plus: ^1.4.0
  path_provider: ^2.0.11
  sliding_up_panel: ^2.0.0+1
  video_player: ^2.4.5
  video_trimmer: ^1.1.2
  visibility_detector: ^0.3.3
  wakelock: ^0.6.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-ExtraLightItalic.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-SemiBoldItalic.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
